### ISSUE TITLE
Version 9 Compatibility

### ISSUE THREAD

**Issue by joshua-igor** [mouse0270/sticky-sidebar#1]
On Version 9 the Sticky Sidebar simply does not work. It does not divide any tabs to show the chat.

**Comment by mouse0270** [comment]
Are there any errors in the console? or anything else you can help me narrow down what might be causing this. As I am using foundry version 9.242 and it appears to be working.

**Comment by KenGitsIt** [comment]
I'm having the same problem.  It also does not appear in the settings screen.  I found this in the console:

````
_module.mjs:3 Uncaught TypeError: Cannot assign to read only property 'name' of function 'class MODULE {
	static name = 'sticky-sidebar';

	static get title() {
		return `${this.name}.title`;
	}

	stat...<omitted>...
}'
[Detected 1 package: unknown:sticky-sidebar]
    at Function.<static_initializer> (_module.mjs:3:16)
    at _module.mjs:1:14````

**Comment by KenGitsIt** [comment]
As a kludge, commenting out line 3 of _module.mjs allows the sticky sidebar to work again, but the settings don't appear.  Replacing all occurrences of `this.name` in that file with `'sticky-sidebar'` makes everything work correctly.

**Comment by mouse0270** [comment]
@KenGitsIt can you do two things for me, can you tell me if you get errors if you have just this module enabled? If you don't get this error with all other modules disabled, can you provide me a list of all your active modules?

**Comment by KenGitsIt** [comment]
I get the same error when I have just this module enabled.

I think it may have started when Chrome installed its latest update.  Setting an appropriate breakpoint in the debugger, I find that MODULE.name is already set to 'MODULE'.

**Comment by KenGitsIt** [comment]
I'm fairly certain it is the new version of Chrome.  With only this module enabled, Sticky Sidebar worked with an old version of Vivaldi, but not the up-to-date Chrome.

**Comment by mouse0270** [comment]
oh its happening in the browser, not the desktop application... let me take a look at it that way

Yup this appears to be an issue in the latest version of chrome based browsers such as chrome, edge and brave. I will take a look at it and see if I can get an update out ASAP. Sorry for this inconvenience

**Comment by mouse0270** [comment]
I figured out the issue, newer versions of chromium must have made `name` a keyword that can't be set inside of a class. So I have fixed this by updating the module to use `ID` instead. I will push an update later today. Thanks for bring this to my attention and helping me resolve it.
